In [16]:
import yfinance as yf 
import pandas as pd 
from datetime import datetime, timedelta
import numpy as np
import matplotlib.pyplot as plt

In [20]:
class GetStockData:
    
    def __init__(self, tickers, start=datetime.today()-timedelta(days=365), end=datetime.today()):
        self.tickers = tickers
        self.stocks_data = yf.download(tickers, start, end)
        
    # gets the data for a specific stock that is in our stocks_data.
    def get_symbol(self, symbol):
        stocks_df = self.stocks_data.loc[:, self.stocks_data.columns.get_level_values(0).isin(["Date"]) | self.stocks_data.columns.get_level_values(1).isin([symbol])]
        return stocks_df
    
    # Get monthly data for a stock or the stocks that were in the ticker
    def monthly_data_ct(self, symbol=None):
        by_month = self.get_symbol(symbol).groupby(pd.Grouper(level="Date",freq="M"))
        full_data_by_month = self.stocks_data.groupby(pd.Grouper(level="Date", freq="M"))
        if symbol == None:
            ct = full_data_by_month
            
        else:
            ct = by_month
        
        # getting central tendency for our dataframe
        result = {"Mean":ct.mean(),
        "Max":ct.max(), "Min":ct.min()}
        result["Mean"].rename_axis("Month", inplace=True)
        result["Mean"].index = result["Mean"].index.strftime('%b-%Y')
        return result
        
        
        

tick = ["AAPL", "MSFT", "TSLA"]



df = GetStockData(tick).monthly_data_ct()["Mean"]

df.columns = [col[0]+" "+col[1] for col in df.columns]
df.rename(columns = {"Date":"Month"})
df.to_csv("stocks_monthly_mean_price.csv")
# df.rename_axis("Month")
# df.index = df.index.strftime("%B")
df

[*********************100%***********************]  3 of 3 completed

,Adj Close AAPL,Adj Close MSFT,Adj Close TSLA,Close AAPL,Close MSFT,Close TSLA,High AAPL,High MSFT,High TSLA,Low AAPL,Low MSFT,Low TSLA,Open AAPL,Open MSFT,Open TSLA,Volume AAPL,Volume MSFT,Volume TSLA
Month,,,,,,,,,,,,,,,,,,
Apr-2022,162.909572,278.913753,321.379528,163.896428,281.649996,321.379528,167.137857,287.597855,334.299050,162.262859,278.539998,315.721431,164.870001,284.034999,327.317860,8.685322e+07,3.263594e+07,7.719831e+07
May-2022,147.708989,264.396266,255.223333,148.430477,266.729046,255.223333,150.950952,270.596665,264.414288,145.364284,262.051428,246.076190,148.324286,266.766190,256.985554,1.143353e+08,3.537629e+07,9.277246e+07
Jun-2022,139.160979,257.576537,234.025873,139.798573,259.499049,234.025873,141.919047,263.016667,241.544444,138.111430,256.189524,228.351111,139.945714,259.192857,234.472539,8.329047e+07,2.958916e+07,9.577276e+07
Jul-2022,148.987878,260.270873,251.394666,149.670499,262.213496,251.394666,150.766000,264.817499,255.841666,147.141500,257.741000,243.754666,148.436499,261.297501,248.886668,7.235627e+07,2.674459e+07,8.724420e+07
Aug-2022,166.315556,278.763721,294.869857,166.885218,280.564350,294.869857,168.589566,283.228258,301.852028,165.533913,278.335216,290.238551,166.956522,280.990870,297.223042,6.566259e+07,2.074598e+07,7.370710e+07
Sep-2022,152.516599,246.396725,288.734763,153.002856,247.709999,288.734763,155.308573,251.147618,294.027140,150.893333,245.154286,282.823809,153.284286,248.519048,287.885710,9.927251e+07,2.740889e+07,6.187005e+07
Oct-2022,144.552467,235.782346,223.810477,145.013333,237.039048,223.810477,146.800478,240.391905,229.788573,142.480476,233.314285,217.481905,144.105716,236.029523,224.126190,8.895903e+07,3.196310e+07,8.263158e+07
Nov-2022,145.586772,236.343528,191.246666,145.843331,237.275237,191.246666,148.032855,240.118096,197.352381,143.508094,233.869048,186.915238,146.057143,236.923809,193.479049,8.213560e+07,2.929981e+07,8.977501e+07
Dec-2022,137.666473,245.028654,152.970476,137.876666,245.642380,152.970476,140.166667,248.537619,158.921428,136.277144,242.601905,150.161429,138.735716,245.819047,155.897143,7.979672e+07,2.815994e+07,1.402023e+08
Jan-2023,135.572004,236.688166,134.195999,135.778999,237.281000,134.195999,137.271498,239.668000,137.242999,133.737001,234.028499,128.430500,135.126000,236.508999,132.316000,7.218262e+07,3.330840e+07,1.948750e+08
Feb-2023,150.883377,259.350614,199.775264,150.968421,259.697370,199.775264,152.296842,262.898948,204.234737,149.011581,257.025787,193.332105,150.226316,260.027372,198.178420,6.879994e+07,3.239479e+07,1.907813e+08
Mar-2023,154.964782,266.742610,188.522609,154.964782,266.742610,188.522609,156.363044,269.377391,192.462608,153.241304,263.262608,184.242608,154.455218,265.844348,188.425218,6.609615e+07,3.250475e+07,1.439676e+08
Apr-2023,165.055000,287.587502,189.482502,165.055000,287.587502,189.482502,165.785000,289.487495,194.625000,163.282501,283.642509,186.505001,164.510002,285.702499,192.707504,5.003908e+07,2.563568e+07,1.384375e+08

In [9]:
df

,Adj Close AAPL,Adj Close MSFT,Adj Close TSLA,Close AAPL,Close MSFT,Close TSLA,High AAPL,High MSFT,High TSLA,Low AAPL,Low MSFT,Low TSLA,Open AAPL,Open MSFT,Open TSLA,Volume AAPL,Volume MSFT,Volume TSLA
Date,,,,,,,,,,,,,,,,,,
2022-04-30,162.909570,278.913760,321.379528,163.896428,281.649996,321.379528,167.137857,287.597855,334.299050,162.262859,278.539998,315.721431,164.870001,284.034999,327.317860,8.685322e+07,3.263594e+07,7.719831e+07
2022-05-31,147.708993,264.396264,255.223333,148.430477,266.729046,255.223333,150.950952,270.596665,264.414288,145.364284,262.051428,246.076190,148.324286,266.766190,256.985554,1.143353e+08,3.537629e+07,9.277246e+07
2022-06-30,139.160979,257.576542,234.025873,139.798573,259.499049,234.025873,141.919047,263.016667,241.544444,138.111430,256.189524,228.351111,139.945714,259.192857,234.472539,8.329047e+07,2.958916e+07,9.577276e+07
2022-07-31,148.987881,260.270877,251.394666,149.670499,262.213496,251.394666,150.766000,264.817499,255.841666,147.141500,257.741000,243.754666,148.436499,261.297501,248.886668,7.235627e+07,2.674459e+07,8.724420e+07
2022-08-31,166.315556,278.763721,294.869857,166.885218,280.564350,294.869857,168.589566,283.228258,301.852028,165.533913,278.335216,290.238551,166.956522,280.990870,297.223042,6.566259e+07,2.074598e+07,7.370710e+07
2022-09-30,152.516594,246.396723,288.734763,153.002856,247.709999,288.734763,155.308573,251.147618,294.027140,150.893333,245.154286,282.823809,153.284286,248.519048,287.885710,9.927251e+07,2.740889e+07,6.187005e+07
2022-10-31,144.552466,235.782345,223.810477,145.013333,237.039048,223.810477,146.800478,240.391905,229.788573,142.480476,233.314285,217.481905,144.105716,236.029523,224.126190,8.895903e+07,3.196310e+07,8.263158e+07
2022-11-30,145.586772,236.343526,191.246666,145.843331,237.275237,191.246666,148.032855,240.118096,197.352381,143.508094,233.869048,186.915238,146.057143,236.923809,193.479049,8.213560e+07,2.929981e+07,8.977501e+07
2022-12-31,137.666473,245.028654,152.970476,137.876666,245.642380,152.970476,140.166667,248.537619,158.921428,136.277144,242.601905,150.161429,138.735716,245.819047,155.897143,7.979672e+07,2.815994e+07,1.402023e+08
2023-01-31,135.572004,236.688166,134.195999,135.778999,237.281000,134.195999,137.271498,239.668000,137.242999,133.737001,234.028499,128.430500,135.126000,236.508999,132.316000,7.218262e+07,3.330840e+07,1.948750e+08
2023-02-28,150.883377,259.350614,199.775264,150.968421,259.697370,199.775264,152.296842,262.898948,204.234737,149.011581,257.025787,193.332105,150.226316,260.027372,198.178420,6.879994e+07,3.239479e+07,1.907813e+08
2023-03-31,154.964782,266.742610,188.522609,154.964782,266.742610,188.522609,156.363044,269.377391,192.462608,153.241304,263.262608,184.242608,154.455218,265.844348,188.425218,6.609615e+07,3.250475e+07,1.439676e+08
2023-04-30,165.055000,287.587502,189.482502,165.055000,287.587502,189.482502,165.785000,289.487495,194.625000,163.282501,283.642509,186.505001,164.510002,285.702499,192.707504,5.003908e+07,2.563568e+07,1.384375e+08